language: python
python:
 - 3.7.2
 - python
 
install:
    - pip install -r requirements.txt

script:
    - ./manage.py test

deploy:
    provider: heroku
    api_key:
        secure: "YOUR ENCRYPTED API KEY"
